### ISSUE TITLE
2주차 백준 문제 고르기

### ISSUE THREAD

**Issue by gunoong011** [gunoong011/DataStructureStudy#3]
정답률 40%이상 문제에서 2문제, 정답률 30~ 40% 문제에서 1문제 선택하기

p.s. 참고로 작년 중간고사에 팰린드롬 나옴

**정답률 40% 이상**

* [1074 Z](https://www.acmicpc.net/problem/1074)
* [1596 영식함수](https://www.acmicpc.net/problem/1596)
* [1784 팰린드롬인코딩](https://www.acmicpc.net/problem/1784)
* [4811 알약](https://www.acmicpc.net/problem/4811)
* [2961 도영이가 만든 맛있는 음식](https://www.acmicpc.net/problem/2961)

**정답률 30 ~ 40%**

* [1019 책 페이지](https://www.acmicpc.net/problem/1019)
* [1135 뉴스 전하기](https://www.acmicpc.net/problem/1135)
* [2257 화학식량](https://www.acmicpc.net/problem/2257)

**Comment by pbt98** [comment]
1596 영식함수, 1019 책 페이지가 적절할것 같은데

**Comment by gunoong011** [comment]
OK! 그러면 1596, 1784, 1019로 결정!
